### ISSUE TITLE
Possible Issue with Path?

### ISSUE THREAD

**Issue by scbean** [naisy/JetsonXavier#1]
I recently re-flashed my Xavier and reinstalled open CV and Tensorflow using this, when I do I get this when I run the real time object detection app.

Also as a side note, I can't seem to find the config.yml file in the download, I see it on GitHub but not when I download the folder.

```
OpenCV(3.4.1) Error: Unspecified error (GStreamer: unable to start pipeline
) in cvCaptureFromCAM_GStreamer, file /mnt/ssd250/compile/opencv-3.4.1/modules/videoio/src/cap_gstreamer.cpp, line 890
VIDEOIO(cvCreateCapture_GStreamer(CV_CAP_GSTREAMER_V4L2, reinterpret_cast<char *>(index))): raised OpenCV exception:

OpenCV(3.4.1) /mnt/ssd250/compile/opencv-3.4.1/modules/videoio/src/cap_gstreamer.cpp:890: error: (-2) GStreamer: unable to start pipeline
 in function cvCaptureFromCAM_GStreamer

Traceback (most recent call last):
  File "run_stream.py", line 127, in main
    detection.start(cfg)
  File "/home/nvidia/Downloads/realtime_object_detection-master/lib/detection_nms_v2.py", line 192, in start
    video_reader.start(VIDEO_INPUT, WIDTH, HEIGHT, save_to_file=SAVE_TO_FILE)
  File "/home/nvidia/Downloads/realtime_object_detection-master/lib/webcam.py", line 74, in start
    raise IOError(("Couldn't open video file or webcam."))
OSError: Couldn't open video file or webcam.

```

**Comment by naisy** [comment]
Hi @scbean,

config.yml is renamed to .config.yml.
You can find with ls command.
`ls -a
`
copy it to config.yml
`cp .config.yml config.yml`

I may change .config.yml later to config.yml.org.

BTW, 
> Error: Unspecified error (GStreamer: unable to start pipeline

This error is probably a mistake in your config.yml.
For Xavier:
`camera_input: "nvarguscamerasrc ! video/x-raw(memory:NVMM), width=1280, height=720,format=NV12, framerate=120/1 ! nvvidconv ! video/x-raw,format=I420 ! videoflip method=rotate-180 ! appsink"`
If you use `nvcamerasrc`, it was already deprecated and it not work on xavier.
See: https://devtalk.nvidia.com/default/topic/1045166/jetson-tx2/nvarguscamerasrc-vs-nvcamerasrc-usage-python-and-opencv-3-4-0/

**Comment by scbean** [comment]
Thanks! Looks like I was using an old config file since I couldn't figure out the `cp .config.yml config.yml`, sorry new to all this...

I thought it might be something else since I wasn't able to get https://jkjung-avt.github.io/tf-trt-models/ to work with the onboard camera or USB camera and had the same error, now I figure it is something related to a difference with the Xavier vs the TX2, thanks for the help!

Now I am onto figure out how to train a new model :)
